#include "headerinfo.h"

#define IMAGE_FILE_32BIT_MACHINE 0x0100
#define IMAGE_FILE_DEBUG_STRIPPED 0x0200
#define IMAGE_FILE_REMOVEABLE_RUN_FROM_SWAP 0x0400
#define IMAGE_FILE_NET_RUM_FROM_SWAP 0x0800

int FileHeaderCharacteristics[] = { IMAGE_FILE_RELOCS_STRIPPED , IMAGE_FILE_EXECUTABLE_IMAGE ,IMAGE_FILE_LINE_NUMS_STRIPPED
,IMAGE_FILE_LOCAL_SYMS_STRIPPED ,IMAGE_FILE_AFFRESIVE_WS_TRIM,IMAGE_FILE_LARGE_ADDRESS_AWARE,IMAGE_FILE_BYTES_REVERSED_LO
,IMAGE_FILE_32BIT_MACHINE,IMAGE_FILE_DEBUG_STRIPPED,IMAGE_FILE_REMOVEABLE_RUN_FROM_SWAP,IMAGE_FILE_NET_RUM_FROM_SWAP
,IMAGE_FILE_SYSTEM ,IMAGE_FILE_DLL ,IMAGE_FILE_UP_SYSTEM_ONLY ,IMAGE_FILE_BYTES_REVERSED_HI };

unsigned char* FileHeaderCharacteristicsMsg[] = { "IMAGE_FILE_RELOCS_STRIPPED" , "IMAGE_FILE_EXECUTABLE_IMAGE" ,"IMAGE_FILE_LINE_NUMS_STRIPPED"
,"IMAGE_FILE_LOCAL_SYMS_STRIPPED" ,"IMAGE_FILE_AFFRESIVE_WS_TRIM","IMAGE_FILE_LARGE_ADDRESS_AWARE","IMAGE_FILE_BYTES_REVERSED_LO"
,"IMAGE_FILE_32BIT_MACHINE", "IMAGE_FILE_DEBUG_STRIPPED", "IMAGE_FILE_REMOVEABLE_RUN_FROM_SWAP", "IMAGE_FILE_NET_RUM_FROM_SWAP"
,"IMAGE_FILE_SYSTEM" ,"IMAGE_FILE_DLL" ,"IMAGE_FILE_UP_SYSTEM_ONLY" ,"IMAGE_FILE_BYTES_REVERSED_HI" };

void CheckCharacteristicsFileHeader(WORD ch) {
	for (int i = 0; i < 11; i++) {
		if ((ch & FileHeaderCharacteristics[i]) == FileHeaderCharacteristics[i]) {
			printf("\t\t\t\t\t%s\n", FileHeaderCharacteristicsMsg[i]);
		}
	}
}